/* Generated By:JavaCC: Do not edit this line. QssConstants.java */
public interface QssConstants {

  int EOF = 0;
  int STRING_LITERAL = 3;
  int CHARACTER_LITERAL = 13;
  int PLUS = 23;
  int MINUS = 24;
  int MULTIPLY = 25;
  int DIVIDE = 26;
  int MODULUS = 27;
  int AND = 28;
  int OR = 29;
  int XOR = 30;
  int NOT = 31;
  int GT = 32;
  int GE = 33;
  int EQ = 34;
  int NEQ = 35;
  int LT = 36;
  int LE = 37;
  int ANDAND = 38;
  int OROR = 39;
  int LP = 40;
  int RP = 41;
  int COUNT = 42;
  int LIST = 43;
  int DESC = 44;
  int UNSET = 45;
  int DOT = 46;
  int INTEGER_LITERAL = 50;
  int DECIMAL_LITERAL = 51;
  int HEX_LITERAL = 52;
  int OCTAL_LITERAL = 53;
  int FLOATING_POINT_LITERAL = 54;
  int EXPONENT = 55;
  int ID = 56;
  int EOL = 57;

  int DEFAULT = 0;
  int WithinString = 1;
  int WithinCharacter = 2;

  String[] tokenImage = {
	"<EOF>",
	"\"\\\"\"",
	"\"\\\'\"",
	"\"\\\"\"",
	"\"\\\\n\"",
	"\"\\\\r\"",
	"\"\\\\\\\\\"",
	"\"\\\\t\"",
	"\"\\\\f\"",
	"\"\\\\b\"",
	"\"\\\\\\\"\"",
	"\"\\\\\\\'\"",
	"<token of kind 12>",
	"\"\\\'\"",
	"\"\\\\n\"",
	"\"\\\\r\"",
	"\"\\\\\\\\\"",
	"\"\\\\t\"",
	"\"\\\\f\"",
	"\"\\\\b\"",
	"\"\\\\\\\"\"",
	"\"\\\\\\\'\"",
	"<token of kind 22>",
	"\"+\"",
	"\"-\"",
	"\"*\"",
	"\"/\"",
	"\"%\"",
	"\"&\"",
	"\"|\"",
	"\"^\"",
	"\"!\"",
	"\">\"",
	"\">=\"",
	"\"==\"",
	"\"!=\"",
	"\"<\"",
	"\"<=\"",
	"\"&&\"",
	"\"||\"",
	"\"(\"",
	"\")\"",
	"\"count\"",
	"\"list\"",
	"\"desc\"",
	"\"unset\"",
	"\".\"",
	"\" \"",
	"\"\\t\"",
	"\"\\r\"",
	"<INTEGER_LITERAL>",
	"<DECIMAL_LITERAL>",
	"<HEX_LITERAL>",
	"<OCTAL_LITERAL>",
	"<FLOATING_POINT_LITERAL>",
	"<EXPONENT>",
	"<ID>",
	"\"\\n\"",
	"\"=\"",
	"\"?\"",
	"\":\"",
	"\",\"",
  };

}
