/* Generated By:JavaCC: Do not edit this line. QssConstants.java */
public interface QssConstants {

  int EOF = 0;
  int CHARACTER_LITERAL = 1;
  int STRING_LITERAL = 2;
  int PLUS = 3;
  int MINUS = 4;
  int MULTIPLY = 5;
  int DIVIDE = 6;
  int MODULUS = 7;
  int AND = 8;
  int OR = 9;
  int XOR = 10;
  int NOT = 11;
  int GT = 12;
  int GE = 13;
  int EQ = 14;
  int NEQ = 15;
  int LT = 16;
  int LE = 17;
  int ANDAND = 18;
  int OROR = 19;
  int LP = 20;
  int RP = 21;
  int COUNT = 22;
  int LIST = 23;
  int DESC = 24;
  int UNSET = 25;
  int DOT = 26;
  int COMMA = 27;
  int SEMICOLON = 28;
  int INTEGER_LITERAL = 32;
  int DECIMAL_LITERAL = 33;
  int HEX_LITERAL = 34;
  int OCTAL_LITERAL = 35;
  int FLOATING_POINT_LITERAL = 36;
  int EXPONENT = 37;
  int ID = 38;
  int EOL = 39;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"!\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\"&&\"",
    "\"||\"",
    "\"(\"",
    "\")\"",
    "\"count\"",
    "\"list\"",
    "\"desc\"",
    "\"unset\"",
    "\".\"",
    "\",\"",
    "\";\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<ID>",
    "\"\\n\"",
    "\"=\"",
    "\"?\"",
    "\":\"",
  };

}
