package org.dianexus.triceps;

/* Generated By:JavaCC: Do not edit this line. QssConstants.java */
public interface QssConstants {

  int EOF = 0;
  int CHARACTER_LITERAL = 1;
  int STRING_LITERAL = 2;
  int PLUS = 3;
  int MINUS = 4;
  int NOT = 5;
  int MULTIPLY = 6;
  int DIVIDE = 7;
  int GT = 8;
  int GE = 9;
  int EQ = 10;
  int NEQ = 11;
  int LT = 12;
  int LE = 13;
  int CONCATENATE = 14;
  int ANDAND = 15;
  int OROR = 16;
  int MODULUS = 17;
  int XOR = 18;
  int AND = 19;
  int OR = 20;
  int ASSIGN = 21;
  int QUEST = 22;
  int COLON = 23;
  int COMMA = 24;
  int LP = 25;
  int RP = 26;
  int LSB = 27;
  int RSB = 28;
  int LCB = 29;
  int RCB = 30;
  int SEMICOLON = 31;
  int INTEGER_LITERAL = 35;
  int DECIMAL_LITERAL = 36;
  int HEX_LITERAL = 37;
  int OCTAL_LITERAL = 38;
  int FLOATING_POINT_LITERAL = 39;
  int EXPONENT = 40;
  int NMTOKEN = 41;
  int EOL = 42;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"+\"",
    "\"-\"",
    "\"!\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\".\"",
    "\"&&\"",
    "\"||\"",
    "\"%\"",
    "\"^\"",
    "\"&\"",
    "\"|\"",
    "\"=\"",
    "\"?\"",
    "\":\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<NMTOKEN>",
    "\"\\n\"",
  };

}
